name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_types:
    name: Lint & Type Check (Node 22)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache Meteor
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: meteor-${{ runner.os }}-3.4-beta.3
      - name: Install Meteor
        run: |
          if ! command -v meteor >/dev/null; then
            curl https://install.meteor.com/ | sh
          fi
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Lint
        run: npm run lint
      - name: Type Check
        run: npm run typecheck

  build:
    name: Meteor Build (Linux)
    runs-on: ubuntu-latest
    needs: lint_and_types
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache Meteor
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: meteor-${{ runner.os }}-3.4-beta.3
      - name: Install Meteor
        run: |
          if ! command -v meteor >/dev/null; then
            curl https://install.meteor.com/ | sh
          fi
      - name: Install deps
        run: npm ci --no-audit --no-fund
      - name: Build (directory)
        run: |
          meteor build ../build --directory
          ls -1 ../build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: meteor-build
          path: ../build
          if-no-files-found: error
